In [1]:
import numpy as np
import sys

changes_range = 0.001
a_range = np.arange(0.01, np.pi / 2, changes_range)
b_range = np.arange(0.01, np.pi / 2, changes_range)

max_value = 0
for a in a_range:
    for b in b_range:
        x = np.linspace(0.01, np.pi, 1000)
        numerator = 2 * np.arcsin((np.sqrt(np.sin((a - b) / 2) ** 2 + np.sin(a) * np.sin(b) * np.sin(x / 2) ** 2)))
        denominator = np.sqrt(a ** 2 + b ** 2 - 2 * a * b * np.cos(x))
        y = numerator / denominator
        max_value = max(max_value, np.max(y))

print(f"{max_value:.8f}")

1.00000000


For each a and b it shows the answer : 

In [2]:
import numpy as np
import matplotlib.pyplot as plt

def calculateAnswer(a, b):
    x = np.linspace(0.01, np.pi, 1000)
    numerator = 2 * np.arcsin((np.sqrt(np.sin((a - b) / 2) ** 2 + np.sin(a) * np.sin(b) * np.sin(x / 2) ** 2)))
    denominator = np.sqrt(a ** 2 + b ** 2 - 2 * a * b * np.cos(x))
    return np.max(numerator / denominator)

changes_range = 0.01
a_range = np.arange(0.01, np.pi / 2, changes_range)
b_range = np.arange(0.01, np.pi / 2, changes_range)
ans = np.zeros((1000, 1000))

for i, a in enumerate(a_range):
    for j, b in enumerate(b_range):
        ans[i, j] = calculateAnswer(a, b)

print(ans)

[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
